name: Deploy frontend (Firebase Hosting)

on:
  push:
    branches: [main]
    paths:
      - 'apps/web/**'
      - 'packages/**'          # if you ever import shared code in the web client

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: pnpm/action-setup@v3
      with: { version: 9.15.9 }

    - uses: actions/setup-node@v4
      with: { node-version: '22' }

    - name: Install deps & build
      run: |
        pnpm install --frozen-lockfile
        pnpm --filter web build

    - name: Deploy to Firebase Hosting
      uses: FirebaseExtended/action-hosting-deploy@v0
      with:
        repoToken: "${{ secrets.GITHUB_TOKEN }}"
        firebaseServiceAccount: "${{ secrets.FIREBASE_TOKEN }}"
        projectId: "${{ secrets.GCLOUD_PROJECT }}"
        channelId: live    # “live” channel == production
        entryPoint: apps/web    # path where firebase.json lives
