name: Deploy backend (Cloud Run)

on:
  push:
    branches: [main]
    paths:
      - 'apps/api/**'
      - 'packages/**'        # shared libs that the API depends on
      - 'Dockerfile'
      - 'pnpm-lock.yaml'

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'      # for WorkloadIdentity if you prefer key-less auth

    steps:
    - uses: actions/checkout@v4

    - uses: pnpm/action-setup@v3
      with: { version: 9.15.9 }

    - uses: actions/setup-node@v4
      with: { node-version: '22' }

    - name: Auth to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCLOUD_SA_KEY }}
        project_id:       ${{ secrets.GCLOUD_PROJECT }}


    - name: Build & push container
      env:
        GCLOUD_REGION: ${{ secrets.GCLOUD_REGION }}
        GCLOUD_PROJECT: ${{ secrets.GCLOUD_PROJECT }}
      run: |
        set -euo pipefail
        GIT_SHA=$(git rev-parse --short HEAD)
        IMAGE="$GCLOUD_REGION-docker.pkg.dev/$GCLOUD_PROJECT/tasteloop-containers/api:$GIT_SHA"
        gcloud builds submit --tag "$IMAGE" .

    - name: Deploy to Cloud Run
      env:
        GCLOUD_REGION: ${{ secrets.GCLOUD_REGION }}
        GCLOUD_PROJECT: ${{ secrets.GCLOUD_PROJECT }}
      run: |
        set -euo pipefail
        GIT_SHA=$(git rev-parse --short HEAD)
        IMAGE="$GCLOUD_REGION-docker.pkg.dev/$GCLOUD_PROJECT/tasteloop-containers/api:$GIT_SHA"
        gcloud run deploy tasteloop-api \
          --image "$IMAGE" \
          --allow-unauthenticated \
          --service-account tasteloop-runner@$GCLOUD_PROJECT.iam.gserviceaccount.com \
          --set-secrets="GEMINI_API_KEY=GEMINI_API_KEY:latest,QLOO_API_KEY=QLOO_API_KEY:latest,MONGODB_URI=MONGODB_URI:latest"

          